# Generated by Django 3.0.2 on 2020-01-05 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('photo_blog', models.ImageField(upload_to='img/blog/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('blog_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
