# Generated by Django 3.0.2 on 2020-01-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo_blog',
            field=models.ImageField(upload_to='blog/%Y/%m/%d/'),
        ),
    ]
