# Generated by Django 3.0.2 on 2020-01-18 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200118_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonal',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
