# Generated by Django 3.0.2 on 2020-01-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_testimonal_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonal',
            new_name='Testimonial',
        ),
    ]
